### ISSUE TITLE
V5, V6 checklist

### ISSUE THREAD

**Issue by dt-rush** [dt-rush/sameriver#88]
V5:
- [ ] BTs
- [ ] Utility
- [ ] Player-centered spatial hashing
- [ ] Despawn/deactivate chunks
- [ ] Perception system (*inside runtimelimiter?*)
- [ ] Terrain grid
- [ ] Perlin noise terrain gen
- [ ] Dstarlite pathfinding with jump diagonal minimization pass
- [ ] Boids demo with steering system

V6:
- [ ] 3D instanced model (static)
- [ ] Vec2/Vec3 replaced with mgl32 types
- [ ] skeleton-animated model
- [ ] save/load world
